version: "3.9"

services:  
  redis:
    image: redis:7.0
    container_name: mercado-bitcoin-api.redis
    command: >
      --appendonly yes
      --port ${REDIS_PORT}
      --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/redis/data

  postgres:
    image: postgres:15.2
    container_name: mercado-bitcoin-api.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres:/postgres/data

  app:
    image: mercado-bitcoin-api:latest
    container_name: mercado-bitcoin-api
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENVIRONMENT: ${APP_ENVIRONMENT}
      APP_HOST: ${APP_HOST}
      APP_HOST_PORT: ${APP_HOST_PORT}
      REDIS_CONNECTION_STRING: ${REDIS_CONNECTION_STRING}
      POSTGRES_CONNECTION_STRING: ${POSTGRES_CONNECTION_STRING}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
    ports:
      - ${APP_HOST_PORT}:${APP_HOST_PORT}

volumes:
  redis:
  postgres:
