version: "3.9"

services:  
  redis:
    image: redis:7.0
    container_name: mercado-bitcoin-api.redis
    command: >
      --appendonly yes
      --port ${REDIS_PORT}
      --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/redis/data

  postgres:
    image: postgres:15.2
    container_name: mercado-bitcoin-api.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres:/postgres/data

volumes:
  redis:
  postgres:
