version: "3.9"

services:  
  postgres:
    image: postgres:15.2
    container_name: mercado-bitcoin-api.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres:/postgres/data

volumes:
  postgres:
