kind: Deployment
apiVersion: apps/v1
metadata:
  name: marcado-bitcoin-api-deployment
  namespace: staging-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marcado-bitcoin-api
  template:
    metadata:
      labels:
        app: marcado-bitcoin-api
    spec:
      containers:
        - name: marcado-bitcoin-api
          image: docker.io/rempeloliveira/public:marcado-bitcoin-api.0.0.1-staging
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: marcado-bitcoin-api-secrets
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
