kind: Service
apiVersion: v1
metadata:
  name: mercado-bitcoin-api-service
  namespace: staging-apps
spec:
  selector:
    app: mercado-bitcoin-api
  type: LoadBalancer
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 80
