kind: Service
apiVersion: v1
metadata:
  name: marcado-bitcoin-api-service
  namespace: staging-apps
spec:
  selector:
    app: marcado-bitcoin-api
  type: LoadBalancer
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 80
