"""AddFieldsOnProductsTable

Revision ID: 35b28c0ea7c4
Revises: d9e5dc7011f6
Create Date: 2023-03-16 10:36:14.972609

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.

revision = '35b28c0ea7c4'
down_revision = 'd9e5dc7011f6'
branch_labels = None
depends_on = 'd9e5dc7011f6'


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column('Products', sa.Column('description', sa.String(), nullable=True))
  op.add_column('Products', sa.Column('price', sa.Float(precision=10, asdecimal=True, decimal_return_scale=2), nullable=True))
  op.add_column('Products', sa.Column('stock', sa.Integer(), nullable=True))
  # ### end Alembic commands ###

def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column('Products', 'stock')
  op.drop_column('Products', 'price')
  op.drop_column('Products', 'description')
  # ### end Alembic commands ###
