name: MercadoBitcoinApi - on-push  ## To run, just push a commit to the working branch.

on:
  push:
    branches:
      - "**"
  workflow_call:

jobs:
  Tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          cache: pip
          cache-dependency-path: requirements/tests.txt
          python-version: 3.10.x

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements/tests.txt
      - name: Tests
        run: |
          make tests

  CodeConvention:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          cache: pip
          cache-dependency-path: requirements/tests.txt
          python-version: 3.10.x

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements/tests.txt
      - name: Code Convention
        run: |
          make code-convention
